(* *********************************************************************)
(*                                                                     *)
(*              The Compcert verified compiler                         *)
(*                                                                     *)
(*                  Xavier Leroy, INRIA Paris                          *)
(*                                                                     *)
(*  Copyright Institut National de Recherche en Informatique et en     *)
(*  Automatique.  All rights reserved.  This file is distributed       *)
(*  under the terms of the INRIA Non-Commercial License Agreement.     *)
(*                                                                     *)
(* *********************************************************************)

(** Translation from Mach to IA32 assembly language *)

Require Import Coqlib Errors.
Require Import AST Integers Floats Memdata.
Require Import Op Locations Mach Asm.

Local Open Scope string_scope.
Local Open Scope error_monad_scope.

(** The code generation functions take advantage of several characteristics of the [Mach] code generated by earlier passes of the compiler:
- Argument and result registers are of the correct type.
- For two-address instructions, the result and the first argument
  are in the same register.  (True by construction in [RTLgen], and preserved by [Reload].)
- The top of the floating-point stack ([ST0], a.k.a. [FP0]) can only
  appear in [mov] instructions, but never in arithmetic instructions.

All these properties are true by construction, but it is painful to track them statically.  Instead, we recheck them during code generation and fail if they do not hold.
*)

(** Extracting integer or float registers. *)

Definition ireg_of (r: mreg) : res ireg :=
  match preg_of r with IR mr => OK mr | _ => Error(msg "Asmgen.ireg_of") end.

Definition freg_of (r: mreg) : res freg :=
  match preg_of r with FR mr => OK mr | _ => Error(msg "Asmgen.freg_of") end.

Section WITHINSTRSIZEMAP.

Variable instr_size_map : instruction -> Z.
Hypothesis instr_size_non_zero : forall i, instr_size_map i > 0.

Definition instr_to_with_info (i: instruction) : instr_with_info :=
  (i, mk_sizeinfo (instr_size_map i) (instr_size_non_zero i)).

Definition code_to_with_info (c: list instruction) : code :=
  map instr_to_with_info c.

(** Smart constructors for some operations. *)

Definition mk_mov (rd rs: preg) (k: code) : res code :=
  match rd, rs with
  | IR rd, IR rs => 
    OK (instr_to_with_info (Pmov_rr rd rs) :: k)
  | FR rd, FR rs => 
    OK (instr_to_with_info (Pmovsd_ff rd rs) :: k)
  | _, _ => Error(msg "Asmgen.mk_mov")
  end.

Definition mk_shrximm (n: int) (k: code) : res code :=
  let p := Int.sub (Int.shl Int.one n) Int.one in
  let l := 
      Ptestl_rr RAX RAX ::
      Pleal RCX (Addrmode (Some RAX) None (inl _ (Int.unsigned p))) ::
      Pcmov Cond_l RAX RCX ::
      Psarl_ri RAX n :: nil in
  let c := code_to_with_info l in
  OK (c ++ k).

Definition mk_shrxlimm (n: int) (k: code) : res code :=
  let l := 
      if Int.eq n Int.zero then Pmov_rr RAX RAX :: nil else
        (Pcqto ::
         Pshrq_ri RDX (Int.sub (Int.repr 64) n) ::
         Pleaq RAX (Addrmode (Some RAX) (Some(RDX, 1)) (inl _ 0)) ::
         Psarq_ri RAX n :: nil) in
  let c := code_to_with_info l in
  OK (c ++ k).

Definition low_ireg (r: ireg) : bool :=
  match r with RAX | RBX | RCX | RDX => true | _ => false end.

Definition mk_intconv (mk: ireg -> ireg -> instruction) (rd rs: ireg) (k: code) :=
  let l := 
      if Archi.ptr64 || low_ireg rs then
        (mk rd rs :: nil)
      else
        (Pmov_rr RAX rs :: mk rd RAX :: nil) in
  OK (code_to_with_info l ++ k).

Definition addressing_mentions (addr: addrmode) (r: ireg) : bool :=
  match addr with Addrmode base displ const =>
      match base with Some r' => ireg_eq r r' | None => false end
   || match displ with Some(r', sc) => ireg_eq r r' | None => false end
  end.

Definition mk_storebyte (addr: addrmode) (rs: ireg) (k: code) :=
  let l := 
      if Archi.ptr64 || low_ireg rs then
        Pmovb_mr addr rs :: nil
      else if addressing_mentions addr RAX then
        Pleal RCX addr :: Pmov_rr RAX rs ::
        Pmovb_mr (Addrmode (Some RCX) None (inl _ 0)) RAX :: nil
      else
        (Pmov_rr RAX rs :: Pmovb_mr addr RAX :: nil) in
  OK (code_to_with_info l ++ k).

(** Accessing slots in the stack frame. *)

Definition loadind (base: ireg) (ofs: ptrofs) (ty: typ) (dst: mreg) (k: code) :=
  do instr <-
  let a := Addrmode (Some base) None (inl _ (Ptrofs.unsigned ofs)) in
  match ty, preg_of dst with
  | Tint, IR r => OK (Pmovl_rm r a)
  | Tlong, IR r => OK (Pmovq_rm r a)
  | Tsingle, FR r => OK (Pmovss_fm r a)
  | Tsingle, ST0  => OK (Pflds_m a)
  | Tfloat, FR r => OK (Pmovsd_fm r a)
  | Tfloat, ST0  => OK (Pfldl_m a)
  | Tany32, IR r => if Archi.ptr64 then Error (msg "Asmgen.loadind1") else OK (Pmov_rm_a r a)
  | Tany64, IR r => if Archi.ptr64 then OK (Pmov_rm_a r a) else Error (msg "Asmgen.loadind2")
  | Tany64, FR r => OK (Pmovsd_fm_a r a)
  | _, _ => Error (msg "Asmgen.loadind")
  end;
  OK (instr_to_with_info instr :: k).

(* Definition loadind (base: ireg) (ofs: ptrofs) (ty: typ) (dst: mreg) (k: code) := *)
(*   let a := Addrmode (Some base) None (inl _ (Ptrofs.unsigned ofs)) in *)
(*   match ty, preg_of dst with *)
(*   | Tint, IR r => OK (instr_to_with_info (Pmovl_rm r a) ::  k) *)
(*   | Tlong, IR r => OK (instr_to_with_info (Pmovq_rm r a) :: k) *)
(*   | Tsingle, FR r => OK (instr_to_with_info (Pmovss_fm r a) :: k) *)
(*   | Tsingle, ST0  => OK (instr_to_with_info (Pflds_m a) :: k) *)
(*   | Tfloat, FR r => OK (instr_to_with_info (Pmovsd_fm r a) :: k) *)
(*   | Tfloat, ST0  => OK (instr_to_with_info (Pfldl_m a) :: k) *)
(*   | Tany32, IR r => if Archi.ptr64 then Error (msg "Asmgen.loadind1") else OK (instr_to_with_info (Pmov_rm_a r a) :: k) *)
(*   | Tany64, IR r => if Archi.ptr64 then OK (instr_to_with_info (Pmov_rm_a r a) :: k) else Error (msg "Asmgen.loadind2") *)
(*   | Tany64, FR r => OK (instr_to_with_info (Pmovsd_fm_a r a) :: k) *)
(*   | _, _ => Error (msg "Asmgen.loadind") *)
(*   end. *)

Definition storeind (src: mreg) (base: ireg) (ofs: ptrofs) (ty: typ) (k: code) :=
  do instr <- 
  let a := Addrmode (Some base) None (inl _ (Ptrofs.unsigned ofs)) in
  match ty, preg_of src with
  | Tint, IR r => OK (Pmovl_mr a r)
  | Tlong, IR r => OK (Pmovq_mr a r)
  | Tsingle, FR r => OK (Pmovss_mf a r)
  | Tsingle, ST0 => OK (Pfstps_m a)
  | Tfloat, FR r => OK (Pmovsd_mf a r)
  | Tfloat, ST0 => OK (Pfstpl_m a)
  | Tany32, IR r => if Archi.ptr64 then Error (msg "Asmgen.storeind1") else OK (Pmov_mr_a a r)
  | Tany64, IR r => if Archi.ptr64 then OK (Pmov_mr_a a r) else Error (msg "Asmgen.storeind2")
  | Tany64, FR r => OK (Pmovsd_mf_a a r)
  | _, _ => Error (msg "Asmgen.storeind")
  end;
  OK (instr_to_with_info instr :: k).

(* Definition storeind (src: mreg) (base: ireg) (ofs: ptrofs) (ty: typ) (k: code) := *)
(*   let a := Addrmode (Some base) None (inl _ (Ptrofs.unsigned ofs)) in *)
(*   match ty, preg_of src with *)
(*   | Tint, IR r => OK (instr_to_with_info (Pmovl_mr a r) :: k) *)
(*   | Tlong, IR r => OK (instr_to_with_info (Pmovq_mr a r) :: k) *)
(*   | Tsingle, FR r => OK (instr_to_with_info (Pmovss_mf a r) :: k) *)
(*   | Tsingle, ST0 => OK (instr_to_with_info (Pfstps_m a) :: k) *)
(*   | Tfloat, FR r => OK (instr_to_with_info (Pmovsd_mf a r) :: k) *)
(*   | Tfloat, ST0 => OK (instr_to_with_info (Pfstpl_m a) :: k) *)
(*   | Tany32, IR r => if Archi.ptr64 then Error (msg "Asmgen.storeind1") else OK (instr_to_with_info (Pmov_mr_a a r) :: k) *)
(*   | Tany64, IR r => if Archi.ptr64 then OK (instr_to_with_info (Pmov_mr_a a r) :: k) else Error (msg "Asmgen.storeind2") *)
(*   | Tany64, FR r => OK (instr_to_with_info (Pmovsd_mf_a a r) :: k) *)
(*   | _, _ => Error (msg "Asmgen.storeind") *)
(*   end. *)

(** Translation of addressing modes *)

Definition transl_addressing (a: addressing) (args: list mreg): res addrmode :=
  match a, args with
  | Aindexed n, a1 :: nil =>
      do r1 <- ireg_of a1; OK(Addrmode (Some r1) None (inl _ n))
  | Aindexed2 n, a1 :: a2 :: nil =>
      do r1 <- ireg_of a1; do r2 <- ireg_of a2;
      OK(Addrmode (Some r1) (Some(r2, 1)) (inl _ n))
  | Ascaled sc n, a1 :: nil =>
      do r1 <- ireg_of a1; OK(Addrmode None (Some(r1, sc)) (inl _ n))
  | Aindexed2scaled sc n, a1 :: a2 :: nil =>
      do r1 <- ireg_of a1; do r2 <- ireg_of a2;
      OK(Addrmode (Some r1) (Some(r2, sc)) (inl _ n))
  | Aglobal id ofs, nil =>
      OK(Addrmode None None (inr _ (id, ofs)))
  | Abased id ofs, a1 :: nil =>
      do r1 <- ireg_of a1; OK(Addrmode (Some r1) None (inr _ (id, ofs)))
  | Abasedscaled sc id ofs, a1 :: nil =>
      do r1 <- ireg_of a1; OK(Addrmode None (Some(r1, sc)) (inr _ (id, ofs)))
  | Ainstack n, nil =>
      OK(Addrmode (Some RSP) None (inl _ (Ptrofs.signed n)))
  | _, _ =>
      Error(msg "Asmgen.transl_addressing")
  end.

Definition normalize_addrmode_32 (a: addrmode) :=
  match a with
  | Addrmode base ofs (inl n) =>
      Addrmode base ofs (inl _ (Int.signed (Int.repr n)))
  | Addrmode base ofs (inr _) =>
      a
  end.

Definition normalize_addrmode_64 (a: addrmode) :=
  match a with
  | Addrmode base ofs (inl n) =>
      let n' := Int.signed (Int.repr n) in
      if zeq n' n
      then (a, None)
      else (Addrmode base ofs (inl _ 0), Some (Int64.repr n))
  | Addrmode base ofs (inr _) =>
      (a, None)
  end.

(** Floating-point comparison.  We swap the operands in some cases
   to simplify the handling of the unordered case. *)

Definition floatcomp (cmp: comparison) (r1 r2: freg) : instruction :=
  match cmp with
  | Clt | Cle => Pcomisd_ff r2 r1
  | Ceq | Cne | Cgt | Cge => Pcomisd_ff r1 r2
  end.

Definition floatcomp32 (cmp: comparison) (r1 r2: freg) : instruction :=
  match cmp with
  | Clt | Cle => Pcomiss_ff r2 r1
  | Ceq | Cne | Cgt | Cge => Pcomiss_ff r1 r2
  end.

(** Translation of a condition.  Prepends to [k] the instructions
  that evaluate the condition and leave its boolean result in bits
  of the condition register. *)

Definition transl_cond
              (cond: condition) (args: list mreg) (k: code) : res code :=
  match cond, args with
  | Ccomp c, a1 :: a2 :: nil =>
      do r1 <- ireg_of a1; do r2 <- ireg_of a2; OK (instr_to_with_info (Pcmpl_rr r1 r2) :: k)
  | Ccompu c, a1 :: a2 :: nil =>
      do r1 <- ireg_of a1; do r2 <- ireg_of a2; OK (instr_to_with_info (Pcmpl_rr r1 r2) :: k)
  | Ccompimm c n, a1 :: nil =>
      do r1 <- ireg_of a1;
      OK (if Int.eq_dec n Int.zero then 
            instr_to_with_info (Ptestl_rr r1 r1) :: k 
          else 
            instr_to_with_info (Pcmpl_ri r1 n) :: k)
  | Ccompuimm c n, a1 :: nil =>
      do r1 <- ireg_of a1; OK (instr_to_with_info (Pcmpl_ri r1 n) :: k)
  | Ccompl c, a1 :: a2 :: nil =>
      do r1 <- ireg_of a1; do r2 <- ireg_of a2; OK (instr_to_with_info (Pcmpq_rr r1 r2) :: k)
  | Ccomplu c, a1 :: a2 :: nil =>
      do r1 <- ireg_of a1; do r2 <- ireg_of a2; OK (instr_to_with_info (Pcmpq_rr r1 r2) :: k)
  | Ccomplimm c n, a1 :: nil =>
      do r1 <- ireg_of a1;
      OK (if Int64.eq_dec n Int64.zero then 
            instr_to_with_info (Ptestq_rr r1 r1) :: k 
          else 
            instr_to_with_info (Pcmpq_ri r1 n) :: k)
  | Ccompluimm c n, a1 :: nil =>
      do r1 <- ireg_of a1; OK (instr_to_with_info (Pcmpq_ri r1 n) :: k)
  | Ccompf cmp, a1 :: a2 :: nil =>
      do r1 <- freg_of a1; do r2 <- freg_of a2; OK (instr_to_with_info (floatcomp cmp r1 r2) :: k)
  | Cnotcompf cmp, a1 :: a2 :: nil =>
      do r1 <- freg_of a1; do r2 <- freg_of a2; OK (instr_to_with_info (floatcomp cmp r1 r2) :: k)
  | Ccompfs cmp, a1 :: a2 :: nil =>
      do r1 <- freg_of a1; do r2 <- freg_of a2; OK (instr_to_with_info (floatcomp32 cmp r1 r2) :: k)
  | Cnotcompfs cmp, a1 :: a2 :: nil =>
      do r1 <- freg_of a1; do r2 <- freg_of a2; OK (instr_to_with_info (floatcomp32 cmp r1 r2) :: k)
  | Cmaskzero n, a1 :: nil =>
      do r1 <- ireg_of a1; OK (instr_to_with_info (Ptestl_ri r1 n) :: k)
  | Cmasknotzero n, a1 :: nil =>
      do r1 <- ireg_of a1; OK (instr_to_with_info (Ptestl_ri r1 n) :: k)
  | _, _ =>
     Error(msg "Asmgen.transl_cond")
  end.

(** What processor condition to test for a given Mach condition. *)

Definition testcond_for_signed_comparison (cmp: comparison) :=
  match cmp with
  | Ceq => Cond_e
  | Cne => Cond_ne
  | Clt => Cond_l
  | Cle => Cond_le
  | Cgt => Cond_g
  | Cge => Cond_ge
  end.

Definition testcond_for_unsigned_comparison (cmp: comparison) :=
  match cmp with
  | Ceq => Cond_e
  | Cne => Cond_ne
  | Clt => Cond_b
  | Cle => Cond_be
  | Cgt => Cond_a
  | Cge => Cond_ae
  end.

Inductive extcond: Type :=
  | Cond_base (c: testcond)
  | Cond_or (c1 c2: testcond)
  | Cond_and (c1 c2: testcond).

Definition testcond_for_condition (cond: condition) : extcond :=
  match cond with
  | Ccomp c => Cond_base(testcond_for_signed_comparison c)
  | Ccompu c => Cond_base(testcond_for_unsigned_comparison c)
  | Ccompimm c n => Cond_base(testcond_for_signed_comparison c)
  | Ccompuimm c n => Cond_base(testcond_for_unsigned_comparison c)
  | Ccompl c => Cond_base(testcond_for_signed_comparison c)
  | Ccomplu c => Cond_base(testcond_for_unsigned_comparison c)
  | Ccomplimm c n => Cond_base(testcond_for_signed_comparison c)
  | Ccompluimm c n => Cond_base(testcond_for_unsigned_comparison c)
  | Ccompf c | Ccompfs c =>
      match c with
      | Ceq => Cond_and Cond_np Cond_e
      | Cne => Cond_or Cond_p Cond_ne
      | Clt => Cond_base Cond_a
      | Cle => Cond_base Cond_ae
      | Cgt => Cond_base Cond_a
      | Cge => Cond_base Cond_ae
      end
  | Cnotcompf c | Cnotcompfs c =>
      match c with
      | Ceq => Cond_or Cond_p Cond_ne
      | Cne => Cond_and Cond_np Cond_e
      | Clt => Cond_base Cond_be
      | Cle => Cond_base Cond_b
      | Cgt => Cond_base Cond_be
      | Cge => Cond_base Cond_b
      end
  | Cmaskzero n => Cond_base Cond_e
  | Cmasknotzero n => Cond_base Cond_ne
  end.

(** Acting upon extended conditions. *)

Definition mk_setcc_base (cond: extcond) (rd: ireg) (k: code) :=
  let l := 
      match cond with
      | Cond_base c =>
        Psetcc c rd :: nil
      | Cond_and c1 c2 =>
        if ireg_eq rd RAX
        then Psetcc c1 RAX :: Psetcc c2 RCX :: Pandl_rr RAX RCX :: nil
        else Psetcc c1 RAX :: Psetcc c2 rd  :: Pandl_rr rd RAX :: nil
      | Cond_or c1 c2 =>
        if ireg_eq rd RAX
        then Psetcc c1 RAX :: Psetcc c2 RCX :: Porl_rr RAX RCX :: nil
        else Psetcc c1 RAX :: Psetcc c2 rd  :: Porl_rr rd RAX :: nil
      end
  in
  code_to_with_info l ++ k.

Definition mk_setcc (cond: extcond) (rd: ireg) (k: code) :=
  if Archi.ptr64 || low_ireg rd
  then mk_setcc_base cond rd k
  else mk_setcc_base cond RAX (instr_to_with_info (Pmov_rr rd RAX) :: k).

Definition mk_jcc (cond: extcond) (lbl: label) (k: code) :=
  let l :=
      match cond with
      | Cond_base c => Pjcc c lbl :: nil
      | Cond_and c1 c2 => Pjcc2 c1 c2 lbl :: nil
      | Cond_or c1 c2 => Pjcc c1 lbl :: Pjcc c2 lbl :: nil
      end
  in
  code_to_with_info l ++ k.

(** Translation of the arithmetic operation [r <- op(args)].
  The corresponding instructions are prepended to [k]. *)

Definition transl_op
             (op: operation) (args: list mreg) (res: mreg) (k: code) : Errors.res code :=
  match op, args with
  | Omove, a1 :: nil =>
      mk_mov (preg_of res) (preg_of a1) k
  | Ointconst n, nil =>
      do r <- ireg_of res;
      OK ((if Int.eq_dec n Int.zero then instr_to_with_info (Pxorl_r r) else instr_to_with_info (Pmovl_ri r n)) :: k)
  | Olongconst n, nil =>
      do r <- ireg_of res;
      OK ((if Int64.eq_dec n Int64.zero then instr_to_with_info (Pxorq_r r) else instr_to_with_info (Pmovq_ri r n)) :: k)
  | Ofloatconst f, nil =>
      do r <- freg_of res;
      OK ((if Float.eq_dec f Float.zero then instr_to_with_info (Pxorpd_f r) else instr_to_with_info (Pmovsd_fi r f)) :: k)
  | Osingleconst f, nil =>
      do r <- freg_of res;
      OK ((if Float32.eq_dec f Float32.zero then instr_to_with_info (Pxorps_f r) else instr_to_with_info (Pmovss_fi r f)) :: k)
  | Oindirectsymbol id, nil =>
      do r <- ireg_of res;
      OK (instr_to_with_info (Pmov_rs r id) :: k)
  | Ocast8signed, a1 :: nil =>
      do r1 <- ireg_of a1; do r <- ireg_of res; mk_intconv Pmovsb_rr r r1 k
  | Ocast8unsigned, a1 :: nil =>
      do r1 <- ireg_of a1; do r <- ireg_of res; mk_intconv Pmovzb_rr r r1 k
  | Ocast16signed, a1 :: nil =>
      do r1 <- ireg_of a1; do r <- ireg_of res; OK (instr_to_with_info (Pmovsw_rr r r1) :: k)
  | Ocast16unsigned, a1 :: nil =>
      do r1 <- ireg_of a1; do r <- ireg_of res; OK (instr_to_with_info (Pmovzw_rr r r1) :: k)
  | Oneg, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pnegl r) :: k)
  | Osub, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Psubl_rr r r2) :: k)
  | Omul, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Pimull_rr r r2) :: k)
  | Omulimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pimull_ri r n) :: k)
  | Omulhs, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq res DX);
      do r2 <- ireg_of a2; OK (instr_to_with_info (Pimull_r r2) :: k)
  | Omulhu, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq res DX);
      do r2 <- ireg_of a2; OK (instr_to_with_info (Pmull_r r2) :: k)
  | Odiv, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res AX);
      OK(instr_to_with_info (Pcltd) :: instr_to_with_info (Pidivl RCX) :: k)
  | Odivu, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res AX);
      OK(instr_to_with_info (Pxorl_r RDX) :: instr_to_with_info (Pdivl RCX) :: k)
  | Omod, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res DX);
      OK(instr_to_with_info (Pcltd) :: instr_to_with_info (Pidivl RCX) :: k)
  | Omodu, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res DX);
      OK(instr_to_with_info (Pxorl_r RDX) :: instr_to_with_info (Pdivl RCX) :: k)
  | Oand, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Pandl_rr r r2) :: k)
  | Oandimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pandl_ri r n) :: k)
  | Oor, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Porl_rr r r2) :: k)
  | Oorimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Porl_ri r n) :: k)
  | Oxor, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Pxorl_rr r r2) :: k)
  | Oxorimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pxorl_ri r n) :: k)
  | Onot, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pnotl r) :: k)
  | Oshl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      assertion (mreg_eq a2 CX);
      do r <- ireg_of res; OK (instr_to_with_info (Psall_rcl r) :: k)
  | Oshlimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Psall_ri r n) :: k)
  | Oshr, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      assertion (mreg_eq a2 CX);
      do r <- ireg_of res; OK (instr_to_with_info (Psarl_rcl r) :: k)
  | Oshrimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Psarl_ri r n) :: k)
  | Oshru, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      assertion (mreg_eq a2 CX);
      do r <- ireg_of res; OK (instr_to_with_info (Pshrl_rcl r) :: k)
  | Oshruimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pshrl_ri r n) :: k)
  | Oshrximm n, a1 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq res AX);
      mk_shrximm n k
  | Ororimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Prorl_ri r n) :: k)
  | Oshldimm n, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Pshld_ri r r2 n) :: k)
  | Olea addr, _ =>
      do am <- transl_addressing addr args; do r <- ireg_of res;
      OK (instr_to_with_info (Pleal r (normalize_addrmode_32 am)) :: k)
(* 64-bit integer operations *)
  | Olowlong, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pmovls_rr r) :: k)
  | Ocast32signed, a1 :: nil =>
      do r1 <- ireg_of a1; do r <- ireg_of res; OK (instr_to_with_info (Pmovsl_rr r r1) :: k)
  | Ocast32unsigned, a1 :: nil =>
      do r1 <- ireg_of a1; do r <- ireg_of res; OK (instr_to_with_info (Pmovzl_rr r r1) :: k)
  | Onegl, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pnegq r) :: k)
  | Oaddlimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Paddq_ri r n) :: k)
  | Osubl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Psubq_rr r r2) :: k)
  | Omull, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Pimulq_rr r r2) :: k)
  | Omullimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pimulq_ri r n) :: k)
  | Omullhs, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq res DX);
      do r2 <- ireg_of a2; OK (instr_to_with_info (Pimulq_r r2) :: k)
  | Omullhu, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq res DX);
      do r2 <- ireg_of a2; OK (instr_to_with_info (Pmulq_r r2) :: k)
  | Odivl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res AX);
      OK(instr_to_with_info (Pcqto) :: instr_to_with_info (Pidivq RCX) :: k)
  | Odivlu, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res AX);
      OK(instr_to_with_info (Pxorq_r RDX) :: instr_to_with_info (Pdivq RCX) :: k)
  | Omodl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res DX);
      OK(instr_to_with_info (Pcqto) :: instr_to_with_info (Pidivq RCX) :: k)
  | Omodlu, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq a2 CX);
      assertion (mreg_eq res DX);
      OK(instr_to_with_info (Pxorq_r RDX) :: instr_to_with_info (Pdivq RCX) :: k)
  | Oandl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Pandq_rr r r2) :: k)
  | Oandlimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pandq_ri r n) :: k)
  | Oorl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Porq_rr r r2) :: k)
  | Oorlimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Porq_ri r n) :: k)
  | Oxorl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; do r2 <- ireg_of a2; OK (instr_to_with_info (Pxorq_rr r r2) :: k)
  | Oxorlimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pxorq_ri r n) :: k)
  | Onotl, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pnotq r) :: k)
  | Oshll, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      assertion (mreg_eq a2 CX);
      do r <- ireg_of res; OK (instr_to_with_info (Psalq_rcl r) :: k)
  | Oshllimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Psalq_ri r n) :: k)
  | Oshrl, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      assertion (mreg_eq a2 CX);
      do r <- ireg_of res; OK (instr_to_with_info (Psarq_rcl r) :: k)
  | Oshrlimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Psarq_ri r n) :: k)
  | Oshrxlimm n, a1 :: nil =>
      assertion (mreg_eq a1 AX);
      assertion (mreg_eq res AX);
      mk_shrxlimm n k
  | Oshrlu, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      assertion (mreg_eq a2 CX);
      do r <- ireg_of res; OK (instr_to_with_info (Pshrq_rcl r) :: k)
  | Oshrluimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Pshrq_ri r n) :: k)
  | Ororlimm n, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- ireg_of res; OK (instr_to_with_info (Prorq_ri r n) :: k)
  | Oleal addr, _ =>
      do am <- transl_addressing addr args; do r <- ireg_of res;
      OK (match normalize_addrmode_64 am with
          | (am', None)       => instr_to_with_info (Pleaq r am') :: k
          | (am', Some delta) => instr_to_with_info (Pleaq r am') :: instr_to_with_info (Paddq_ri r delta) :: k
          end)
(**)
  | Onegf, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; OK (instr_to_with_info (Pnegd r) :: k)
  | Oabsf, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; OK (instr_to_with_info (Pabsd r) :: k)
  | Oaddf, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Paddd_ff r r2) :: k)
  | Osubf, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Psubd_ff r r2) :: k)
  | Omulf, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Pmuld_ff r r2) :: k)
  | Odivf, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Pdivd_ff r r2) :: k)
  | Onegfs, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; OK (instr_to_with_info (Pnegs r) :: k)
  | Oabsfs, a1 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; OK (instr_to_with_info (Pabss r) :: k)
  | Oaddfs, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Padds_ff r r2) :: k)
  | Osubfs, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Psubs_ff r r2) :: k)
  | Omulfs, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Pmuls_ff r r2) :: k)
  | Odivfs, a1 :: a2 :: nil =>
      assertion (mreg_eq a1 res);
      do r <- freg_of res; do r2 <- freg_of a2; OK (instr_to_with_info (Pdivs_ff r r2) :: k)
  | Osingleoffloat, a1 :: nil =>
      do r <- freg_of res; do r1 <- freg_of a1; OK (instr_to_with_info (Pcvtsd2ss_ff r r1) :: k)
  | Ofloatofsingle, a1 :: nil =>
      do r <- freg_of res; do r1 <- freg_of a1; OK (instr_to_with_info (Pcvtss2sd_ff r r1) :: k)
  | Ointoffloat, a1 :: nil =>
      do r <- ireg_of res; do r1 <- freg_of a1; OK (instr_to_with_info (Pcvttsd2si_rf r r1) :: k)
  | Ofloatofint, a1 :: nil =>
      do r <- freg_of res; do r1 <- ireg_of a1; OK (instr_to_with_info (Pcvtsi2sd_fr r r1) :: k)
  | Ointofsingle, a1 :: nil =>
      do r <- ireg_of res; do r1 <- freg_of a1; OK (instr_to_with_info (Pcvttss2si_rf r r1) :: k)
  | Osingleofint, a1 :: nil =>
      do r <- freg_of res; do r1 <- ireg_of a1; OK (instr_to_with_info (Pcvtsi2ss_fr r r1) :: k)
  | Olongoffloat, a1 :: nil =>
      do r <- ireg_of res; do r1 <- freg_of a1; OK (instr_to_with_info (Pcvttsd2sl_rf r r1) :: k)
  | Ofloatoflong, a1 :: nil =>
      do r <- freg_of res; do r1 <- ireg_of a1; OK (instr_to_with_info (Pcvtsl2sd_fr r r1) :: k)
  | Olongofsingle, a1 :: nil =>
      do r <- ireg_of res; do r1 <- freg_of a1; OK (instr_to_with_info (Pcvttss2sl_rf r r1) :: k)
  | Osingleoflong, a1 :: nil =>
      do r <- freg_of res; do r1 <- ireg_of a1; OK (instr_to_with_info (Pcvtsl2ss_fr r r1) :: k)
  | Ocmp c, args =>
      do r <- ireg_of res;
      transl_cond c args (mk_setcc (testcond_for_condition c) r k)
  | _, _ =>
      Error(msg "Asmgen.transl_op")
  end.

(** Translation of memory loads and stores *)

Definition transl_load (chunk: memory_chunk)
                       (addr: addressing) (args: list mreg) (dest: mreg)
                       (k: code) : res code :=
  do instr <-
  do am <- transl_addressing addr args;
  match chunk with
  | Mint8unsigned =>
      do r <- ireg_of dest; OK(Pmovzb_rm r am)
  | Mint8signed =>
      do r <- ireg_of dest; OK(Pmovsb_rm r am)
  | Mint16unsigned =>
      do r <- ireg_of dest; OK(Pmovzw_rm r am)
  | Mint16signed =>
      do r <- ireg_of dest; OK(Pmovsw_rm r am)
  | Mint32 =>
      do r <- ireg_of dest; OK(Pmovl_rm r am)
  | Mint64 =>
      do r <- ireg_of dest; OK(Pmovq_rm r am)
  | Mfloat32 =>
      do r <- freg_of dest; OK(Pmovss_fm r am)
  | Mfloat64 =>
      do r <- freg_of dest; OK(Pmovsd_fm r am)
  | _ =>
      Error (msg "Asmgen.transl_load")
  end;
  OK (instr_to_with_info instr :: k).

Definition transl_store (chunk: memory_chunk)
                        (addr: addressing) (args: list mreg) (src: mreg)
                        (k: code) : res code :=
  do am <- transl_addressing addr args;
  match chunk with
  | Mint8unsigned | Mint8signed =>
      do r <- ireg_of src; mk_storebyte am r k
  | Mint16unsigned | Mint16signed =>
      do r <- ireg_of src; OK(instr_to_with_info (Pmovw_mr am r) :: k)
  | Mint32 =>
      do r <- ireg_of src; OK(instr_to_with_info (Pmovl_mr am r) :: k)
  | Mint64 =>
      do r <- ireg_of src; OK(instr_to_with_info (Pmovq_mr am r) :: k)
  | Mfloat32 =>
      do r <- freg_of src; OK(instr_to_with_info (Pmovss_mf am r) :: k)
  | Mfloat64 =>
      do r <- freg_of src; OK(instr_to_with_info (Pmovsd_mf am r) :: k)
  | _ =>
      Error (msg "Asmgen.transl_store")
  end.

(** Translation of a Mach instruction. *)

Definition transl_instr (f: Mach.function) (i: Mach.instruction)
                        (ax_is_parent: bool) (k: code) :=
  match i with
  | Mgetstack ofs ty dst =>
      loadind RSP ofs ty dst k
  | Msetstack src ofs ty =>
      storeind src RSP ofs ty k
  | Mgetparam ofs ty dst =>
      if ax_is_parent then
        loadind RAX ofs ty dst k
      else
        (do k1 <- loadind RAX ofs ty dst k;
           OK (instr_to_with_info (Pload_parent_pointer RAX (StackADT.frame_size (Mach.fn_frame f))) :: k1)
           (* loadind RSP f.(fn_link_ofs) Tptr AX k1 *))
  | Mop op args res =>
      transl_op op args res k
  | Mload chunk addr args dst =>
      transl_load chunk addr args dst k
  | Mstore chunk addr args src =>
      transl_store chunk addr args src k
  | Mcall sig (inl reg) =>
      do r <- ireg_of reg; OK (instr_to_with_info (Pcall_r r sig) :: k)
  | Mcall sig (inr symb) =>
      OK (instr_to_with_info (Pcall_s symb sig) :: k)
  | Mtailcall sig (inl reg) =>
      do r <- ireg_of reg;
      OK (instr_to_with_info (Pfreeframe (StackADT.frame_size (f.(Mach.fn_frame))) f.(fn_retaddr_ofs)) ::
          instr_to_with_info (Pjmp_r r sig) :: k)
  | Mtailcall sig (inr symb) =>
      OK (instr_to_with_info (Pfreeframe (StackADT.frame_size (Mach.fn_frame f)) f.(fn_retaddr_ofs)) ::
          instr_to_with_info (Pjmp_s symb sig) :: k)
  | Mlabel lbl =>
      OK(instr_to_with_info (Plabel lbl) :: k)
  | Mgoto lbl =>
      OK(instr_to_with_info (Pjmp_l lbl) :: k)
  | Mcond cond args lbl =>
      transl_cond cond args (mk_jcc (testcond_for_condition cond) lbl k)
  | Mjumptable arg tbl =>
      do r <- ireg_of arg; OK (instr_to_with_info (Pjmptbl r tbl) :: k)
  | Mreturn =>
      OK (instr_to_with_info (Pfreeframe (StackADT.frame_size (Mach.fn_frame f)) f.(fn_retaddr_ofs)) ::
          instr_to_with_info (Pret) :: k)
  | Mbuiltin ef args res =>
      OK (instr_to_with_info (Pbuiltin ef (List.map (map_builtin_arg preg_of) args) (map_builtin_res preg_of res)) :: k)
  end.

(** Translation of a code sequence *)

Definition it1_is_parent (before: bool) (i: Mach.instruction) : bool :=
  match i with
  | Msetstack src ofs ty => before
  | Mgetparam ofs ty dst => negb (mreg_eq dst AX)
  | _ => false
  end.

(** This is the naive definition that we no longer use because it
  is not tail-recursive.  It is kept as specification. *)

Fixpoint transl_code (f: Mach.function) (il: list Mach.instruction) (axp: bool) :=
  match il with
  | nil => OK nil
  | i1 :: il' =>
      do k <- transl_code f il' (it1_is_parent axp i1);
      transl_instr f i1 axp k
  end.

(** This is an equivalent definition in continuation-passing style
  that runs in constant stack space. *)

Fixpoint transl_code_rec (f: Mach.function) (il: list Mach.instruction)
                         (axp: bool) (k: code -> res code) :=
  match il with
  | nil => k nil
  | i1 :: il' =>
      transl_code_rec f il' (it1_is_parent axp i1)
        (fun c1 => do c2 <- transl_instr f i1 axp c1; k c2)
  end.

Definition transl_code' (f: Mach.function) (il: list Mach.instruction) (axp: bool) :=
  transl_code_rec f il axp (fun c => OK c).

(** Translation of a whole function.  Note that we must check
  that the generated code contains less than [2^32] instructions,
  otherwise the offset part of the [PC] code pointer could wrap
  around, leading to incorrect executions. *)

Definition transl_function (f: Mach.function) :=
  do c <- transl_code' f f.(Mach.fn_code) true;
  OK (mkfunction f.(Mach.fn_sig)
                     (instr_to_with_info (Pallocframe f.(Mach.fn_frame) f.(fn_retaddr_ofs)) :: c)
                     (f.(Mach.fn_frame))).

Definition transf_function (f: Mach.function) : res Asm.function :=
  do tf <- transl_function f;
  if zlt Ptrofs.max_unsigned (code_size tf.(fn_code))
  then Error (msg "code size exceeded")
  else OK tf.

Definition transf_fundef (f: Mach.fundef) : res Asm.fundef :=
  transf_partial_fundef transf_function f.

Definition transf_program (p: Mach.program) : res Asm.program :=
  transform_partial_program transf_fundef p.

End WITHINSTRSIZEMAP.